# Source this from the other scripts (Linux / WSL / macOS): toolchain, venv and data paths.
# Every setting can be overridden from the environment.
if [ -f "$HOME/.cargo/env" ]; then source "$HOME/.cargo/env"; fi
export PATH="$HOME/.local/bin:$PATH"
# Repository root (the parent of scripts/).
export PROJ="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$PROJ/target}"
export RAYON_NUM_THREADS="${RAYON_NUM_THREADS:-4}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"
# Python venv used by the scripts (created by setup_env.sh).
export VENV="${FASTTEXT_NEW_VENV:-$PROJ/.venv}"
# Models, corpora and training data (downloaded / generated by setup_env.sh, never committed).
export FASTTEXT_NEW_DATA="${FASTTEXT_NEW_DATA:-$PROJ/data}"
export DATA="$FASTTEXT_NEW_DATA"
